[package]
name = "rust-diesel-mysql"
version = "0.1.0"
authors = ["alextanhongpin <alextan@seekasia.com>"]

[dependencies]
dotenv = "0.11.0"

[dependencies.diesel]
version = "1.2.2"
features = ["mysql"]
