version: '3.6'
services:
  mysql:
    image: mysql:8.0.11
    environment:
    # This is required for the error mentioned
    # - MYSQL_ROOT_PASSWORD=123456
    # - MYSQL_PASSWORD=123456
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=root
    - MYSQL_DATABASE=test
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ./tmp/mysql:/var/lib/mysql
    ports:
    - 127.0.0.1:3306:3306