[package]
name = "rust-mysql"
version = "0.1.0"
authors = ["alextanhongpin <alextan@seekasia.com>"]

[dependencies]
r2d2 = "0.8.2"
rustc-serialize = "0.3.24"
mysql = "12.2.0"

[dependencies.r2d2_mysql]
version = "9.0.0"
git = "https://github.com/outersky/r2d2-mysql"

