[package]
name = "rust-mysql"
version = "0.1.0"
authors = ["alextanhongpin <alextan@seekasia.com>"]

[dependencies]
r2d2 = "0.8.2"

[dependencies.r2d2_mysql]
# version = "8.0.0"
git = "https://github.com/outersky/r2d2-mysql"
version = "*"

[dependencies.mysql]
version = "12.3.1"